### ISSUE TITLE
Trying to follow the example --

### ISSUE THREAD

**Issue by jahbini** [bmatcuk/html-brunch-static#1]
I have put in the three example files ***layouts/main.jade***, ***partials/greetings.html***, and ***index.md*** in the app directory.   I included the example for the brunch-config.coffee.

However, no output for these files!  On close inspection, the extensions are not sufficient.  As written, jade-brunch-static, etc. require the extension '.static.jade'

This is not covered in your example, and it would be inconvenient to tag static files in this manner (at least for my application) -- How do I actually use your good offerings?  I would really like to have all the "static" files originate from a "site" directory (rather than "app", "vendor" or "assets")

possible?

**Comment by bmatcuk** [comment]
Sorry for the slow reply: github _just_ sent me an email about your issue =(

You're correct: the example isn't quite right. I'll update the documentation.

In the meantime, it should be possible to do what you want to do. Both the jade and markdown processors have the `fileMatch` and `fileTransform` options. The `fileMatch` option is what determines the input filename (ie, the `.static.jade` extension). The `fileTransform` option determines how the input filename will be transformed into a .html extension (ie, replacing `.static.jade` with `.html`).

If you want all of your static files to live in a `site/` directory instead of `app/`, you could configure this in your `brunch-config.coffee`. A minimal example is below:

```coffee
exports.config =
  paths:
    watched: ['site', 'app', 'test', 'vendor']

  files: {}

  plugins:
    static:
      processors: [
        require('html-brunch-static') {
          processors: [
            require('marked-brunch-static')(fileMatch: "site/**/*.md", fileTransform: (f) -> f.replace(/md$/, 'html'))
            require('jade-brunch-static')(fileMatch: "site/**/*.jade", fileTransform: ((f) -> f.replace(/jade$/, 'html')), pretty: true)
          ]
        }
      ]
```

Notice how the `fileMatch` option was set to `"site/**/*.md"` and `"site/**/*.jade"`. This will ensure that html-brunch-static will only operate on files in the `site` directory. Additionally, the `fileTransform` options were set to replace `md` or `jade` with `html` respectively. And lastly, the `site` directory was added to brunch's list of "watched" files.

Using this `brunch-config.coffee`, you should be able to move `index.md`, `partials/greetings.html`, and `layouts/main.jade` over to your `site` directory and it should work... I just tested it =)

Please ensure that you have the latest version of [marked-brunch-static](https://github.com/bmatcuk/marked-brunch-static) and [jade-brunch-static](https://github.com/bmatcuk/jade-brunch-static). I just updated them both to v1.1.0 and published them to npm.

Let me know if you have any more trouble.

**Comment by jahbini** [comment]
Big time thank you!

I will rev my stuff ASAP.

James Hinds
jahbini@icloud.com <mailto:jahbini@icloud.com>
PS: it sez you are in HNL.  Say Hi for me to Peter Kay

**Comment by bmatcuk** [comment]
No problem! Let me know if you run into any more trouble!

**Comment by jahbini** [comment]
I just revved and tested.  Alas.
The code, for your inspection is on branch 'bootstrap' of repository jahbini/brunch-with-chaplin-static

The file "log.txt" is the result of the command: "brunch build -debug 2>log.txt"

When the build is done, the files 'index.html' and 'index.md' are placed in the 'public' directory, but have the identical contents: "app/layouts/main.jade" -- a single line of a file name that doesn't exist.

**Comment by bmatcuk** [comment]
Oh, sorry, forgot to mention that you'll need to update the paths to the layout and partial in `index.md` to match your new directory structure. The front matter for `index.md` should look like this:

```yaml
---
title: html-brunch-static's awesome test page
_options:
  layout: site/layouts/main.jade
  partials:
    - site/partials/greetings.html
---
```

I think that should solve your problem.

**Comment by jahbini** [comment]
Just as you said: I rechecked where 'app/layouts/main.jade' is coming from -- it's in the front matter for index.md -- 

changing that to 
```
'''
title: html-brunch-static's awesome test page
_options:
  layout: site/layouts/main.jade
  partials:
    - site/partials/greetings.html
'''
```

Does help: However, the index.html is now
```
<!DOCTYPE html>
<html>
  <head>
    <title>html-brunch-static&#x27;s awesome test page</title>
  </head>
  <body></body>
</html>
```

The <body> is missing all the text from index.ms

**Comment by bmatcuk** [comment]
Hmm, not sure what the issue is... I cloned your repo, made the updates to index.md (changed `app` to `site`), and ran brunch build... looks like it works for me. Here's my full index.md:

```markdown
---
title: html-brunch-static's awesome test page
_options:
  layout: site/layouts/main.jade
  partials:
    - site/partials/greetings.html
---
{{>greetings}}

This is **html-brunch-static's** super awesome test page.
```

**Comment by jahbini** [comment]
Found my problem:  the value "content" for the jade template is everything after the front matter in the ".md" file, and must be referred to as "content", not "contents"

You might mention the exact spelling is required in the jade template.

**Comment by bmatcuk** [comment]
Glad you got it working =)
